export const BOOKING_STATUS_FLOW: Record<string, string[]> = {
  PENDING: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['ASSIGNED', 'CANCEL_REQUESTED'],
  ASSIGNED: ['COMPLETED', 'CANCEL_REQUESTED'],
  CANCEL_REQUESTED: ['CANCELLED'],
  COMPLETED: [],
  CANCELLED: [],
};
